

PLANT_PAX_MODULES = ["P_ANALOG_INPUT", "P_ANALOG_OUTPUT", "P_DISCRETE_INPUT", "P_DISCRETE_OUTPUT",
                     "P_VALVE_DISCRETE", "P_VARIABLE_SPEED_DRIVE", "P_MOTOR_DISCRETE", "P_PID", "P_D4SD"]
PV_MODULE_TYPES = ["P_ANALOG_INPUT"]
CV_MODULE_TYPES = ["P_VARIABLE_SPEED_DRIVE", "P_PID", "P_ANALOG_OUTPUT"]
VALVE_TYPES = ["P_VALVE_DISCRETE"]
MODEL_TYPES = ["None", "Flow", "Pressure", "Temperature", "Level"]
COLUMN_HEADINGS = ["Analog Input", "Active", "Device Type", "Value", "Model"]
COLUMN_WIDTHS = [150, 60, 120, 80, 120]